In [1]:
import random as rd
import pandas as pd
import numpy as np
import regex as re
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as s
import scipy.stats as ss
import warnings 
warnings.filterwarnings('ignore')
import nltk
from nltk.tokenize import sent_tokenize,word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer,LancasterStemmer,SnowballStemmer,WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
import emoji
from textblob import TextBlob

In [6]:
data = pd.read_csv(r"C:\Users\HP\Downloads\nyka_top_brands_cosmetics_product_reviews\nyka_top_brands_cosmetics_product_reviews.csv")

* converted my csv file into dataframe

In [7]:
data.columns

Index(['product_id', 'brand_name', 'review_id', 'review_title', 'review_text',
       'author', 'review_date', 'review_rating', 'is_a_buyer', 'pro_user',
       'review_label', 'product_title', 'mrp', 'price', 'product_rating',
       'product_rating_count', 'product_tags', 'product_url'],
      dtype='object')

* these all are the columns which are present in dataframe

In [8]:
data

,product_id,brand_name,review_id,review_title,review_text,author,review_date,review_rating,is_a_buyer,pro_user,review_label,product_title,mrp,price,product_rating,product_rating_count,product_tags,product_url
0,781070,Olay,16752142,Worth buying 50g one,Works as it claims. Could see the difference f...,Ashton Dsouza,2021-01-23 15:17:18,5.0,True,False,Verified Buyer,Olay Ultra Lightweight Moisturiser: Luminous W...,1999,1599,4.1,43,NaN,https://www.nykaa.com/olay-ultra-lightweight-m...
1,781070,Olay,14682550,Best cream to start ur day,It does what it claims . Best thing is it smoo...,Amrit Neelam,2020-09-07 15:30:42,5.0,True,False,Verified Buyer,Olay Ultra Lightweight Moisturiser: Luminous W...,1999,1599,4.1,43,NaN,https://www.nykaa.com/olay-ultra-lightweight-m...
2,781070,Olay,15618995,perfect for summers dry for winters,I have been using this product for months now....,Sanchi Gupta,2020-11-13 12:24:14,4.0,True,False,Verified Buyer,Olay Ultra Lightweight Moisturiser: Luminous W...,1999,1599,4.1,43,NaN,https://www.nykaa.com/olay-ultra-lightweight-m...
3,781070,Olay,13474509,Not a moisturizer,"i have an oily skin, while this whip acts as a...",Ruchi Shah,2020-06-14 11:56:50,3.0,True,False,Verified Buyer,Olay Ultra Lightweight Moisturiser: Luminous W...,1999,1599,4.1,43,NaN,https://www.nykaa.com/olay-ultra-lightweight-m...
4,781070,Olay,16338982,Average,It's not that good. Please refresh try for oth...,Sukanya Sarkar,2020-12-22 15:24:35,2.0,True,False,Verified Buyer,Olay Ultra Lightweight Moisturiser: Luminous W...,1999,1599,4.1,43,NaN,https://www.nykaa.com/olay-ultra-lightweight-m...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61279,1044490,Herbal Essences,17769058,Good,I use this thrice a week. Has helped me in mak...,Radhesh,2021-04-12 13:28:41,5.0,True,False,Verified Buyer,Herbal Essences Aloe & Eucalyptus Shampoo For ...,750,525,4.3,512,FEATURED,https://www.nykaa.com/herbal-essences-potent-a...
61280,1044490,Herbal Essences,17766838,Great,This shampoo has a amazing fragnance and textu...,Shalini Sirohi,2021-04-12 11:47:07,5.0,True,False,Verified Buyer,Herbal Essences Aloe & Eucalyptus Shampoo For ...,750,525,4.3,512,FEATURED,https://www.nykaa.com/herbal-essences-potent-a...
61281,1044490,Herbal Essences,17765866,Really mild and nice,"Used it for the first time, feels really fresh...",Sana kanted,2021-04-12 10:58:34,5.0,True,False,Verified Buyer,Herbal Essences Aloe & Eucalyptus Shampoo For ...,750,525,4.3,512,FEATURED,https://www.nykaa.com/herbal-essences-potent-a...
61282,1044490,Herbal Essences,17761057,Amazing product!,One of the best shampoo which are sulphate and...,neeru chouhan,2021-04-11 21:44:55,5.0,True,False,Verified Buyer,Herbal Essences Aloe & Eucalyptus Shampoo For ...,750,525,4.3,512,FEATURED,https://www.nykaa.com/herbal-essences-potent-a...
61283,4633369,Colorbar,25987603,Not good,It is so irritating so bad i don't like this much,Mssuhv,2022-06-20 17:41:52,2.0,False,False,NaN,Colorbar Mogra Mist - Scent Of An India Temple...,595,417,1.5,2,NaN,https://www.nykaa.com/colorbar-mogra-mist-scen...

In [9]:
data.isnull().sum()

product_id                  0
brand_name                  0
review_id                   0
review_title                0
review_text                 8
author                      0
review_date                 0
review_rating               1
is_a_buyer                  0
pro_user                    0
review_label            13035
product_title               0
mrp                         0
price                       0
product_rating              0
product_rating_count        0
product_tags            47782
product_url                 0
dtype: int64

* In this dataframe 4 columns contains null values

In [10]:
data=data.drop(["product_tags"],axis=1)

* in product_tags column contains morethan 50% data having NAN values so dropped this column

In [11]:
data.review_text.mode()

0    Good
Name: review_text, dtype: object

In [12]:
data["review_label"]=data["review_label"].fillna("Verified Buyer")
data["review_rating"]=data["review_rating"].fillna("5.0")
data["review_text"]=data["review_text"].fillna("Good")

* successfully filled with their modes

In [13]:
data.isnull().sum()

product_id              0
brand_name              0
review_id               0
review_title            0
review_text             0
author                  0
review_date             0
review_rating           0
is_a_buyer              0
pro_user                0
review_label            0
product_title           0
mrp                     0
price                   0
product_rating          0
product_rating_count    0
product_url             0
dtype: int64

In [14]:
data1 = data.head()

* taken 5 datapoints on the top of the data

In [15]:
sw = stopwords.words("english")

* saving all the stopwords

In [16]:
b_n=[]
for i in data["review_text"]:
    l=[]
    ls=i.lower()
    ls=re.sub("[^a-zA-Z ]","",ls)
    ls=emoji.demojize(ls)
    for word in word_tokenize(ls):
        if word in sw:
            pass
        else:
            stems=PorterStemmer().stem(word)
            l.append(stems)
    b_n.append(" ".join(l))

* text pre-processing steps

In [17]:
d = pd.DataFrame({"cleaned_data":b_n})

* after completion of pre-processing i have get cleaned data

In [19]:
d1=d.head()

* this is the cleaned data

## BAG OF WORDS VECTORS (COUNT VECTORIZER)

In [20]:
cv = CountVectorizer()
t_array = cv.fit_transform(d1.cleaned_data).toarray()
vocabulary = cv.vocabulary_

In [21]:
pd.DataFrame(t_array,columns=sorted(vocabulary))

,absorb,act,base,best,buy,claim,cleanser,combin,could,day,...,still,thing,tri,ur,use,well,whip,winter,work,worth
0,0,0,0,1,0,1,1,0,1,1,...,0,0,0,0,1,0,0,0,1,0
1,0,0,0,1,0,1,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
2,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,1,0,1,1,0
3,0,1,1,0,1,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

## TFIDF VECTORIZER

In [29]:
tf = TfidfVectorizer()
tr = tf.fit_transform(d1.cleaned_data).toarray()

In [30]:
pd.DataFrame(tr,columns=sorted(tf.vocabulary_))

,absorb,act,base,best,buy,claim,cleanser,combin,could,day,...,still,thing,tri,ur,use,well,whip,winter,work,worth
0,0.000000,0.000000,0.000000,0.247762,0.000000,0.247762,0.307094,0.000000,0.307094,0.307094,...,0.000000,0.000000,0.000000,0.000000,0.247762,0.000000,0.000000,0.000000,0.247762,0.000000
1,0.000000,0.000000,0.000000,0.296558,0.000000,0.296558,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.367576,0.000000,0.367576,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.270141,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.270141,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.217948,0.270141,0.000000,0.270141,0.217948,0.000000
3,0.000000,0.212806,0.212806,0.000000,0.212806,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.212806,0.000000,0.000000,0.000000,0.000000,0.000000,0.212806,0.000000,0.000000,0.212806
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.463693,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

## ONE HOT ENCODER

In [24]:
oh=OneHotEncoder()
con_da=oh.fit_transform(data[["brand_name"]])
values=con_da.toarray()

In [25]:
pd.DataFrame(values,columns=oh.categories_).applymap(int)

,Colorbar,Herbal Essences,Kay Beauty,L'Oreal Paris,Lakme,Maybelline New York,NYX Professional Makeup,Nivea,Nykaa Cosmetics,Nykaa Naturals,Olay
0,0,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
61279,0,1,0,0,0,0,0,0,0,0,0
61280,0,1,0,0,0,0,0,0,0,0,0
61281,0,1,0,0,0,0,0,0,0,0,0
61282,0,1,0,0,0,0,0,0,0,0,0
61283,1,0,0,0,0,0,0,0,0,0,0